# Generated by Django 3.2.11 on 2022-01-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aligner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceword',
            name='features',
            field=models.CharField(blank=True, default='None Provided', max_length=30, null=True),
        ),
    ]
