# Generated by Django 3.2.11 on 2022-02-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aligner', '0003_auto_20220131_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishword',
            name='sent_aligned',
            field=models.CharField(default='None Provided', max_length=30),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='sent_aligned',
            field=models.CharField(default='None Provided', max_length=30),
        ),
        migrations.AddField(
            model_name='latinword',
            name='sent_aligned',
            field=models.CharField(default='None Provided', max_length=30),
        ),
    ]
