# Generated by Django 3.2.11 on 2022-02-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aligner', '0004_auto_20220201_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='sent_aligned',
            field=models.CharField(blank=True, default='None Provided', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='frenchword',
            name='sent_aligned',
            field=models.CharField(blank=True, default='None Provided', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='latinword',
            name='sent_aligned',
            field=models.CharField(blank=True, default='None Provided', max_length=30, null=True),
        ),
    ]
