# Generated by Django 3.2.11 on 2022-02-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aligner', '0006_auto_20220221_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frenchword',
            name='en_sent_id',
            field=models.IntegerField(blank=True, default='None Provided', null=True),
        ),
        migrations.AlterField(
            model_name='frenchword',
            name='la_sent_id',
            field=models.IntegerField(blank=True, default='None Provided', null=True),
        ),
    ]
