# Generated by Django 3.2.11 on 2022-03-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aligner', '0008_auto_20220222_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishword',
            name='chapter_number',
            field=models.CharField(blank=True, default='None Provided', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='chapter_number',
            field=models.CharField(blank=True, default='None Provided', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='latinword',
            name='chapter_number',
            field=models.CharField(blank=True, default='None Provided', max_length=30, null=True),
        ),
    ]
